#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu linux distro.
# The installed server listens to port 80 (HTTP) for connection
# And serves a default page index.html on the HTTP  GET request.
# print "Hello World"

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee file /var/www/html/index.html
sudo service nginx restart
